=== wilians123/duca_bot/contrato/contrato.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://duca-t.local/contrato.schema.json",
  "title": "DucaTForm",
  "type": "object",
  "properties": {
    "hasDiscrepancies": {
      "type": "boolean"
    },
    "discrepancyDetails": {
      "type": [
        "null",
        "string"
      ]
    },
    "paso1": {
      "type": "object",
      "properties": {
        "PaisProcedencia": {
          "type": [
            "null",
            "string"
          ]
        },
        "AduanaInicio": {
          "type": [
            "null",
            "string"
          ]
        },
        "PaisDestino": {
          "type": [
            "null",
            "string"
          ]
        },
        "AduanaDestino": {
          "type": [
            "null",
            "string"
          ]
        },
        "Observaciones": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "PaisProcedencia",
        "AduanaInicio",
        "PaisDestino",
        "AduanaDestino",
        "Observaciones"
      ],
      "additionalProperties": false
    },
    "paso2": {
      "type": "object",
      "properties": {
        "NombreExportador": {
          "type": [
            "null",
            "string"
          ]
        },
        "DomicilioExportador": {
          "type": [
            "null",
            "string"
          ]
        },
        "TipoIdentificacionExportador": {
          "type": [
            "null",
            "string"
          ]
        },
        "NumeroIdentificacionExportador": {
          "type": [
            "null",
            "string"
          ]
        },
        "PaisExportador": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "NombreExportador",
        "DomicilioExportador",
        "TipoIdentificacionExportador",
        "NumeroIdentificacionExportador",
        "PaisExportador"
      ],
      "additionalProperties": false
    },
    "paso3": {
      "type": "object",
      "properties": {
        "NombreImportador": {
          "type": [
            "null",
            "string"
          ]
        },
        "DomicilioImportador": {
          "type": [
            "null",
            "string"
          ]
        },
        "TipoIdentificacionImportador": {
          "type": [
            "null",
            "string"
          ]
        },
        "NumeroIdentificacionImportador": {
          "type": [
            "null",
            "string"
          ]
        },
        "PaisImportador": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "NombreImportador",
        "DomicilioImportador",
        "TipoIdentificacionImportador",
        "NumeroIdentificacionImportador",
        "PaisImportador"
      ],
      "additionalProperties": false
    },
    "paso4": {
      "type": "object",
      "properties": {
        "AduanaPaso": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "AduanaPaso"
      ],
      "additionalProperties": false
    },
    "paso5": {
      "type": "object",
      "properties": {
        "CodigoTransportista": {
          "type": [
            "null"
          ]
        },
        "PlacaTransporte": {
          "type": [
            "null"
          ]
        }
      },
      "required": [
        "CodigoTransportista",
        "PlacaTransporte"
      ],
      "additionalProperties": false
    },
    "paso6": {
      "type": "object",
      "properties": {
        "LicenciaConductor": {
          "type": [
            "null"
          ]
        }
      },
      "required": [
        "LicenciaConductor"
      ],
      "additionalProperties": false
    },
    "paso7": {
      "type": "object",
      "properties": {
        "gastos": {
          "type": "object",
          "properties": {
            "ValorFOB": {
              "type": [
                "null",
                "number",
                "string"
              ]
            },
            "GastosTransporte": {
              "type": [
                "null",
                "number",
                "string"
              ]
            },
            "GastosSeguro": {
              "type": [
                "null",
                "number",
                "string"
              ]
            },
            "OtrosGastos": {
              "type": [
                "null",
                "number",
                "string"
              ]
            },
            "ValorTotal": {
              "type": [
                "null",
                "number",
                "string"
              ]
            }
          },
          "required": [
            "ValorFOB",
            "GastosTransporte",
            "GastosSeguro",
            "OtrosGastos",
            "ValorTotal"
          ],
          "additionalProperties": false
        },
        "mercancias": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "PartidaArancelaria": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "DescripcionMercancia": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "CantidadMercancia": {
                "type": [
                  "null",
                  "number",
                  "string"
                ]
              },
              "ClaseMercancia": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "PaisMercancia": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "PesoMercancia": {
                "type": [
                  "null",
                  "number",
                  "string"
                ]
              }
            },
            "required": [
              "PartidaArancelaria",
              "DescripcionMercancia",
              "CantidadMercancia",
              "ClaseMercancia",
              "PaisMercancia",
              "PesoMercancia"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "gastos",
        "mercancias"
      ],
      "additionalProperties": false
    },
    "paso8": {
      "type": "object",
      "properties": {
        "cartaporte": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "NombreDocumentoPorte": {
                "type": [
                  "null"
                ]
              },
              "TipoDocumentoPorte": {
                "type": [
                  "null"
                ]
              },
              "NumeroDocumentoPorte": {
                "type": [
                  "null"
                ]
              }
            },
            "required": [
              "NombreDocumentoPorte",
              "TipoDocumentoPorte",
              "NumeroDocumentoPorte"
            ],
            "additionalProperties": false
          }
        },
        "facturas": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "NombreDocumentoFactura": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "TipoDocumentoFactura": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "NumeroDocumentoFactura": {
                "type": [
                  "null",
                  "string"
                ]
              }
            },
            "required": [
              "NombreDocumentoFactura",
              "TipoDocumentoFactura",
              "NumeroDocumentoFactura"
            ],
            "additionalProperties": false
          }
        },
        "manifiestos": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "NombreDocumentoManifiesto": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "TipoDocumentoManifiesto": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "NumeroDocumentoManifiesto": {
                "type": [
                  "null",
                  "string"
                ]
              }
            },
            "required": [
              "NombreDocumentoManifiesto",
              "TipoDocumentoManifiesto",
              "NumeroDocumentoManifiesto"
            ],
            "additionalProperties": false
          }
        },
        "otros": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "NombreDocumentoBL": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "TipoDocumentoManifiestoBL": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "NumeroDocumentoManifiestoBL": {
                "type": [
                  "null",
                  "string"
                ]
              }
            },
            "required": [
              "NombreDocumentoBL",
              "TipoDocumentoManifiestoBL",
              "NumeroDocumentoManifiestoBL"
            ],
            "additionalProperties": false
          }
        }
      },
      "required": [
        "cartaporte",
        "facturas",
        "manifiestos",
        "otros"
      ],
      "additionalProperties": false
    },
    "paso9": {
      "type": "object",
      "properties": {
        "TipoEquipamiento": {
          "type": [
            "null",
            "string"
          ]
        },
        "TipoCarga": {
          "type": [
            "null",
            "string"
          ]
        },
        "PlacaChasis": {
          "type": [
            "null"
          ]
        },
        "MarchamoSat": {
          "type": [
            "null",
            "string"
          ]
        },
        "TamañoContenedor": {
          "type": [
            "null",
            "string"
          ]
        },
        "NumeroContenedor": {
          "type": [
            "null",
            "string"
          ]
        },
        "PaisChasis": {
          "type": [
            "null"
          ]
        }
      },
      "required": [
        "TipoEquipamiento",
        "TipoCarga",
        "PlacaChasis",
        "MarchamoSat",
        "TamañoContenedor",
        "NumeroContenedor",
        "PaisChasis"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "hasDiscrepancies",
    "discrepancyDetails",
    "paso1",
    "paso2",
    "paso3",
    "paso4",
    "paso5",
    "paso6",
    "paso7",
    "paso8",
    "paso9"
  ],
  "additionalProperties": false
}

=== wilians123/duca_bot/contrato/fixtures/embarque_3.json
{
  "hasDiscrepancies": true,
  "discrepancyDetails": "{\"campo\": \"BUQUE\", \"valores\": [{\"valor\": \"A. OBELIX\", \"fuente\": \"NAM8689177-MN.pdf (VESSEL)\"}, {\"valor\": \"CMA CGM KAILAS\", \"fuente\": \"NAM8689177-OBL.pdf (VESSEL)\"}]}; {\"campo\": \"VIAJE\", \"valores\": [{\"valor\": \"YUK000N19\", \"fuente\": \"NAM8689177-MN.pdf (VOYAGE)\"}, {\"valor\": \"0UAO3S1MA\", \"fuente\": \"NAM8689177-OBL.pdf (VOYAGE NUMBER)\"}]}",
  "paso1": {
    "AduanaDestino": "ALM.GRAL.DEPOSITO OCCIDENTE (APOPA) - 83 - ADUANA PORTUARIA",
    "Observaciones": "MBL: NAM8689177 BUQUE A. OBELIX VIAJE YUK000N19 FECHA 21-SEP-26. EN TRANSITO A AGDOSA RANSA, APOPA CODIGO 83. AGENTE DESPACHADOR CMA CGM GASTOS DE SEGURO $1.00, GASTOS DE TRANSPORTE $1.00 UNICAMENTE PARA EFECTOS DEL REGISTRO ADUANERO.",
    "PaisProcedencia": "GUATEMALA",
    "PaisDestino": "EL SALVADOR",
    "AduanaInicio": "ADUANA SANTO TOMAS DE CASTILLA - ST - ADUANA PORTUARIA"
  },
  "paso2": {
    "TipoIdentificacionExportador": "NÚMERO DE IDENTIFICACIÓN TRIBUTARIA",
    "NumeroIdentificacionExportador": "S/N",
    "PaisExportador": "ESTADOS UNIDOS",
    "NombreExportador": "B & C LUXURY AUTO LTD",
    "DomicilioExportador": "104 LISTER AVE NEWARK US"
  },
  "paso3": {
    "NombreImportador": "B&C LUXURY AUTO SA DE CV",
    "PaisImportador": "EL SALVADOR",
    "NumeroIdentificacionImportador": "06141111201069",
    "TipoIdentificacionImportador": "NÚMERO DE IDENTIFICACIÓN TRIBUTARIA",
    "DomicilioImportador": "CALLE MANUEL ENRIQUE ARAUJO CENTRO COMERCIAL LA MASCOTA LOCAL 5 SAN SALVADOR SV"
  },
  "paso4": {
    "AduanaPaso": "ADUANA LA ERMITA LE ADUANA FRONTERA"
  },
  "paso5": {
    "CodigoTransportista": null,
    "PlacaTransporte": null
  },
  "paso6": {
    "LicenciaConductor": null
  },
  "paso7": {
    "mercancias": [
      {
        "PesoMercancia": "1378.01",
        "ClaseMercancia": "VN",
        "DescripcionMercancia": "VIN:3N1AB8CV2MY207279 2021 NISSAN SENTRA RED",
        "PaisMercancia": "ESTADOS UNIDOS",
        "PartidaArancelaria": "87032369910",
        "CantidadMercancia": "1"
      },
      {
        "PesoMercancia": "1349.89",
        "ClaseMercancia": "VN",
        "DescripcionMercancia": "VIN:5NPD84LFXJH389400 2018 HYUNDAI ELANTRA BLACK",
        "PaisMercancia": "ESTADOS UNIDOS",
        "PartidaArancelaria": "87032369910",
        "CantidadMercancia": "1"
      },
      {
        "PesoMercancia": "995.18",
        "ClaseMercancia": "VN",
        "DescripcionMercancia": "VIN:ML32F4FJ8LHF06198 2020 MITSUBISHI MIRAGE G4 MAROON",
        "PaisMercancia": "ESTADOS UNIDOS",
        "PartidaArancelaria": "87032259910",
        "CantidadMercancia": "1"
      },
      {
        "PesoMercancia": "980.21",
        "ClaseMercancia": "VN",
        "DescripcionMercancia": "VIN:ML32FUFJ9RHF04520 2024 MITSUBISHI MIRAGE G4 RED",
        "PaisMercancia": "ESTADOS UNIDOS",
        "PartidaArancelaria": "87032259910",
        "CantidadMercancia": "1"
      },
      {
        "PesoMercancia": "1397.06",
        "ClaseMercancia": "VN",
        "DescripcionMercancia": "VIN:3N1AB8BV1NY232158 2022 NISSAN SENTRA GRAY",
        "PaisMercancia": "ESTADOS UNIDOS",
        "PartidaArancelaria": "87032369910",
        "CantidadMercancia": "1"
      },
      {
        "PesoMercancia": "1290.02",
        "ClaseMercancia": "VN",
        "DescripcionMercancia": "VIN:5NPD84LF2LH582952 2020 HYUNDAI ELANTRA SILVER",
        "PaisMercancia": "ESTADOS UNIDOS",
        "PartidaArancelaria": "87032369910",
        "CantidadMercancia": "1"
      }
    ],
    "gastos": {
      "ValorTotal": null,
      "ValorFOB": "14535.66",
      "GastosTransporte": null,
      "GastosSeguro": null,
      "OtrosGastos": null
    }
  },
  "paso8": {
    "cartaporte": [],
    "facturas": [
      {
        "NombreDocumentoFactura": "Consol Facturas (52).pdf",
        "TipoDocumentoFactura": "FACTURA COMERCIAL",
        "NumeroDocumentoFactura": "27237452/57957556/27290163/55757916/62971466/27277013"
      }
    ],
    "manifiestos": [
      {
        "NombreDocumentoManifiesto": "NAM8689177-MN.pdf",
        "TipoDocumentoManifiesto": "MANIFIESTO DE CARGA",
        "NumeroDocumentoManifiesto": "CC126001086"
      }
    ],
    "otros": [
      {
        "NombreDocumentoBL": "NAM8689177-OBL.pdf",
        "TipoDocumentoManifiestoBL": "Conocimiento de embarque máster",
        "NumeroDocumentoManifiestoBL": "NAM8689177"
      }
    ]
  },
  "paso9": {
    "TipoCarga": "CONTENERIZADA",
    "NumeroContenedor": "TDRU9580107",
    "MarchamoSat": "SAT-GT 732668",
    "PaisChasis": null,
    "TipoEquipamiento": "CONTENEDOR",
    "TamañoContenedor": "45",
    "PlacaChasis": null
  }
}

=== wilians123/duca_bot/contrato/fixtures/embarque_2.json
{
  "hasDiscrepancies": false,
  "discrepancyDetails": null,
  "paso1": {
    "AduanaDestino": "TERRESTRE ANGUIATÚ - 08 - ADUANA PORTUARIA",
    "Observaciones": "MBL: BGA0529993 BUQUE LITTLE SYMPHONY VIAJE 0YKDLN1MA FECHA 02-09-2026. EN TRANSITO A FRONTERA ANGUIATU CODIGO 08. AGENTE DESPACHADOR CMA CGM GASTOS DE SEGURO $1.00, GASTOS DE TRANSPORTE $1.00 UNICAMENTE PARA EFECTOS DEL REGISTRO ADUANERO.",
    "PaisProcedencia": "GUATEMALA",
    "AduanaInicio": "ADUANA SANTO TOMAS DE CASTILLA - ST - ADUANA PORTUARIA",
    "PaisDestino": "EL SALVADOR"
  },
  "paso2": {
    "PaisExportador": "COLOMBIA",
    "TipoIdentificacionExportador": "NÚMERO DE IDENTIFICACIÓN TRIBUTARIA",
    "NumeroIdentificacionExportador": "890302609-0",
    "DomicilioExportador": "CRA 7 No. 34-120 CALI, COLOMBIA",
    "NombreExportador": "SONOCO DE COLOMBIA LTDA"
  },
  "paso3": {
    "NombreImportador": "FAMPRO TISSUE EL SALVADOR LTDA DE CV",
    "TipoIdentificacionImportador": "NÚMERO DE IDENTIFICACIÓN TRIBUTARIA",
    "PaisImportador": "EL SALVADOR",
    "DomicilioImportador": "KM 32 1/2 CARRETERA A SAN JUAN OPICO SITIO DEL NINO, LA LIBERTAD, LA LIBERTAD",
    "NumeroIdentificacionImportador": "0623291025104"
  },
  "paso4": {
    "AduanaPaso": "ADUANA LA ERMITA LE ADUANA FRONTERA"
  },
  "paso5": {
    "CodigoTransportista": null,
    "PlacaTransporte": null
  },
  "paso6": {
    "LicenciaConductor": null
  },
  "paso7": {
    "mercancias": [
      {
        "ClaseMercancia": "PK",
        "PaisMercancia": "COLOMBIA",
        "PesoMercancia": 6606.08,
        "CantidadMercancia": 208,
        "PartidaArancelaria": "48229000",
        "DescripcionMercancia": "TUBOS DE CARTON"
      }
    ],
    "gastos": {
      "ValorFOB": 15040.38,
      "ValorTotal": null,
      "GastosSeguro": 0,
      "OtrosGastos": null,
      "GastosTransporte": 0
    }
  },
  "paso8": {
    "cartaporte": [],
    "facturas": [
      {
        "NombreDocumentoFactura": "001 FACTURA CGT3870 (1).pdf",
        "TipoDocumentoFactura": "FACTURA COMERCIAL",
        "NumeroDocumentoFactura": "CGT3870"
      }
    ],
    "manifiestos": [
      {
        "NombreDocumentoManifiesto": "026 MANIFIESTO BGA9993 (1).pdf",
        "TipoDocumentoManifiesto": "MANIFIESTO DE CARGA",
        "NumeroDocumentoManifiesto": null
      }
    ],
    "otros": [
      {
        "NombreDocumentoBL": "020 BL BGA0529993 (1).pdf",
        "TipoDocumentoManifiestoBL": "Conocimiento de embarque máster",
        "NumeroDocumentoManifiestoBL": "BGA0529993"
      }
    ]
  },
  "paso9": {
    "TipoEquipamiento": "CONTENEDOR",
    "MarchamoSat": null,
    "PlacaChasis": null,
    "TipoCarga": "CONTENERIZADA",
    "NumeroContenedor": "FFAU1602875",
    "TamañoContenedor": "40",
    "PaisChasis": null
  }
}

=== wilians123/duca_bot/contrato/fixtures/embarque_1.json
{
  "hasDiscrepancies": true,
  "discrepancyDetails": "{\"campo\": \"BUQUE\", \"valorCorreo\": null, \"documentoOrigenCorreo\": \"Cuerpo del correo\", \"valorDocumento\": \"LITTLE SYMPHONY\", \"documentoOrigenDocumento\": \"YUK020N19.pdf\"}; {\"campo\": \"VIAJE\", \"valorCorreo\": null, \"documentoOrigenCorreo\": \"Cuerpo del correo\", \"valorDocumento\": \"YUK020N19\", \"documentoOrigenDocumento\": \"YUK020N19.pdf\"}; {\"campo\": \"FECHA\", \"valorCorreo\": null, \"documentoOrigenCorreo\": \"Cuerpo del correo\", \"valorDocumento\": \"12-10-2026\", \"documentoOrigenDocumento\": \"YUK020N19.pdf\"}",
  "paso1": {
    "PaisProcedencia": "GUATEMALA",
    "AduanaDestino": "ALM.GRAL.DEPOSITO OCCIDENTE (APOPA) - 83 - ADUANA PORTUARIA",
    "Observaciones": "MBL: NAM8722259 BUQUE LITTLE SYMPHONY VIAJE YUK020N19 FECHA 12-10-2026. EN TRANSITO A ALM.GRAL.DEPOSITO OCCIDENTE (APOPA) CODIGO 83. AGENTE DESPACHADOR CMA CGM GASTOS DE SEGURO $1.00, GASTOS DE TRANSPORTE $1.00 UNICAMENTE PARA EFECTOS DEL REGISTRO ADUANERO.",
    "PaisDestino": "EL SALVADOR",
    "AduanaInicio": "ADUANA SANTO TOMAS DE CASTILLA - ST - ADUANA PORTUARIA"
  },
  "paso2": {
    "NumeroIdentificacionExportador": "S/N",
    "NombreExportador": "DECO ART",
    "TipoIdentificacionExportador": "NÚMERO DE IDENTIFICACIÓN TRIBUTARIA",
    "PaisExportador": "ESTADOS UNIDOS",
    "DomicilioExportador": "PO Box 297 Stanford, KY 40484 USA"
  },
  "paso3": {
    "TipoIdentificacionImportador": "NÚMERO DE IDENTIFICACIÓN TRIBUTARIA",
    "NumeroIdentificacionImportador": "06141103211055",
    "PaisImportador": "EL SALVADOR",
    "NombreImportador": "SOLUCIONES LOGISTICAS DE CENTROAMERICA S.A, DE C.V",
    "DomicilioImportador": "AV. BALBOA, EDIFICIO PH ART & YOO PARQUE INDUSTRIAL ORION BLOQUE A LOCAL 2 CIUDAD ARCE, LA LIBERTAD, El Salvador"
  },
  "paso4": {
    "AduanaPaso": "ADUANA LA ERMITA LE ADUANA FRONTERA"
  },
  "paso5": {
    "CodigoTransportista": null,
    "PlacaTransporte": null
  },
  "paso6": {
    "LicenciaConductor": null
  },
  "paso7": {
    "mercancias": [
      {
        "PesoMercancia": 19428.595,
        "PartidaArancelaria": "3213.90.00.00",
        "ClaseMercancia": "PK",
        "PaisMercancia": "US",
        "DescripcionMercancia": "PINTURA ACRILICA AZUL CIELO",
        "CantidadMercancia": 21
      }
    ],
    "gastos": {
      "GastosTransporte": null,
      "GastosSeguro": null,
      "OtrosGastos": null,
      "ValorFOB": 50816.16,
      "ValorTotal": null
    }
  },
  "paso8": {
    "cartaporte": [],
    "facturas": [
      {
        "NombreDocumentoFactura": "INV (11).pdf",
        "TipoDocumentoFactura": "FACTURA COMERCIAL",
        "NumeroDocumentoFactura": "D370427"
      }
    ],
    "manifiestos": [
      {
        "NombreDocumentoManifiesto": "YUK020N19.pdf",
        "TipoDocumentoManifiesto": "MANIFIESTO DE CARGA",
        "NumeroDocumentoManifiesto": null
      }
    ],
    "otros": [
      {
        "NombreDocumentoBL": "NAM8722259 (1).pdf",
        "TipoDocumentoManifiestoBL": "Conocimiento de embarque máster",
        "NumeroDocumentoManifiestoBL": "NAM8722259"
      }
    ]
  },
  "paso9": {
    "PlacaChasis": null,
    "PaisChasis": null,
    "TipoCarga": "CONTENERIZADA",
    "TipoEquipamiento": "CONTENEDOR",
    "NumeroContenedor": "SEGU6953570",
    "MarchamoSat": null,
    "TamañoContenedor": "40"
  }
}
